# Generated by Django 4.0.1 on 2022-06-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='image',
            new_name='image_url',
        ),
    ]
